name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0' # Adjust to your Qt version
        modules: 'qtcharts' # Add modules if needed

    - name: Setup environment
      run: |
        echo "QTDIR=$HOME/Qt/6.5.0/$(uname -s)-$(uname -m)/lib/cmake" >> $GITHUB_ENV
        echo "PATH=$HOME/Qt/6.5.0/$(uname -s)-$(uname -m)/bin:$PATH" >> $GITHUB_ENV

    - name: Configure and build
      run: |
        qmake
        make

    - name: Run tests
      run: |
        ./TicTacToe # Adjust executable name based on your TARGET

    - name: Deploy (optional)
      if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
      run: |
        echo "Deploying to production..."
        # Add deployment steps (e.g., copy to server, create package)
